---
openapi: 3.0.3
servers:
  - url: /api
info:
  title: Graph API
  version: '1.0.0'
tags:
  - name: Graph
paths:
  /graph/bfs:
    post:
      tags:
        - Graph
      operationId: bfs
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Graph"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string

  /graph/dfs:
    post:
      tags:
        - Graph
      operationId: dfs
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Graph"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string

components:
  schemas:
    Graph:
      type: object
      properties:
        graph:
          type: object
          additionalProperties:
            type: array
            items:
              type: string
          example:
            A: [ "B", "C" ]
            B: [ "D" ]
            C: [ ]
            D: [ ]
        startNode:
          type: string
          example: "A"
